# Configuration file for components/repositories
# This file defines the list of all components used across the project
# Used by installation and deployment scripts to maintain consistency

asap-tools
asap-common
#FlinkSketch
#QueryEngine
asap-query-engine
asap-planner
asap-planner-rs
#prometheus-kafka-adapter
asap-summary-ingest
asap-quickstart
asap-tools/data-sources/prometheus-exporters
asap-tools/queriers/prometheus-client
asap-tools/execution-utilities
