# Configuration file for components/repositories
# This file defines the list of all components used across the project
# Used by installation and deployment scripts to maintain consistency

asap-tools
asap-common
#FlinkSketch
#QueryEngine
sketchlib-rust
asap-query-engine
asap-planner
#prometheus-kafka-adapter
asap-sketch-ingest
asap-quickstart
asap-tools/prometheus-exporters
asap-tools/prometheus-client
asap-tools/execution-utilities
