aggregations:
- aggregationId: 21
  aggregationSubType: ''
  aggregationType: DatasketchesKLL
  labels:
    aggregated: []
    grouping:
    - dstip
    - proto
    - srcip
    rollup: []
  metric: netflow_table
  parameters:
    K: 20
  slideInterval: 1
  spatialFilter: ''
  table_name: netflow_table
  value_column: pkt_len
  windowSize: 1
  windowType: tumbling
tables:
- name: netflow_table
  time_column: time
  value_columns:
  - pkt_len
  metadata_columns:
  - srcip
  - dstip
  - proto
