output_dir: "/app/outputs"
log_level: "INFO"
prometheus_scrape_interval_ms: 1000
streaming_engine: "precompute"

http_server:
  port: 8088

backend:
  type: "prometheus"
  server: "http://prometheus:9090"
  forward_unsupported_queries: true

store:
  lock_strategy: "per-key"

ingest:
  type: "http_remote_write"
  port: 9091

inference_config: "/asap-planner-output/inference_config.yaml"
streaming_config: "/asap-planner-output/streaming_config.yaml"
