tables:
  - name: h2o_groupby
    time_column: timestamp
    metadata_columns: [id1, id2]
    value_columns: [v1]

aggregations:
  - aggregationId: 12
    aggregationType: DatasketchesKLL
    aggregationSubType: ''
    labels:
      grouping: [id1, id2]
      rollup: []
      aggregated: []
    table_name: h2o_groupby
    value_column: v1
    parameters:
      K: 200
    windowSizeMs: 10000
    windowType: tumbling
    spatialFilter: ''
